### ISSUE TITLE
Project is not using a CSS convention

### ISSUE THREAD

**Issue by romgrk** [pranavtharoor/micm-project-match#1]
There is no CSS convention in use, which leads to very particular selectors (illustrated below). Those selectors don't carry meaning, and it's hard to know what is being styled just by looking at the stylesheet.

![Screenshot from 2019-07-24 12-42-48](https://user-images.githubusercontent.com/1423607/61811948-92603880-ae10-11e9-9f16-16d83f9fc818.png)

For example, using the [BEM](http://getbem.com/introduction/) convention, these would be written as:
```css
.UserProfile__field {
 font-weight: 400;
}
.UserProfile__link {
 color: blue;
 /* ... */
}
```
The BEM convention helps avoid specificity issues and makes things more readable.
